### PR TITLE
Shastra OS - Team Page #55

### PR DESCRIPTION
**Pull request by nooras**
Fix: #55 

Team Page of Shastra OS site.

Video:
ShastraOsTeamPage

Screenshot:
image

### CODE REVIEW

**Comment by adityyaa-10** [comment]
Looks good to me @nooras

**Review by vivekpal1 — APPROVED** [review]
It looks good

**Comment by nooras** [comment]
> It looks good, but I think profile picture is huge on Desktops

Okkay will reduce its size

**Comment by adityyaa-10** [comment]
Hi @nooras I've fixed the size issue.

**Comment by nooras** [comment]
Wooh Great @adityyaa-10 🙌

**Pull request merged**
